config/routes.rb
Cookiejar::Application.routes.draw do
  resources :cookie_jars do

    collection do
      post 'update_level'
    end

  end

  root :to => "cookie_jars#index"

end

app/models/cookie_jar.rb
class CookieJar < ActiveRecord::Base
  attr_accessible :level
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cookie_jars_controller.rb
class CookieJarsController < ApplicationController
  # GET /cookie_jars
  # GET /cookie_jars.json
  def index
    @cookie_jars = CookieJar.all

    @the_cookie_jar = CookieJar.find(3)

    @level = @the_cookie_jar.level

    if @level <100 && @level > 89
      @level = 90
    elsif @level <90 && @level > 79
      @level = 80
    elsif @level <80 && @level > 69
       @level = 70
    elsif @level <70 && @level > 59
       @level = 60
    elsif @level <60 && @level > 49
       @level = 50
    elsif @level <50 && @level > 39
       @level = 40
    elsif @level <40 && @level > 29
       @level = 30
    elsif @level <30 && @level > 19
        @level = 20
    elsif @level <20 && @level > 9
         @level = 10
    elsif @level < 10 && @level > 5
        @level = 5
    end
   
    if @level > 100
      @level = 100
    end
        

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cookie_jars }
    end
  end

  def update_level
    index = params[:level]
    the_cookie_jar = CookieJar.find(3)
    the_cookie_jar.level = index
    the_cookie_jar.save
  end

  # GET /cookie_jars/1
  # GET /cookie_jars/1.json
  def show
    @cookie_jar = CookieJar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cookie_jar }
    end
  end

  # GET /cookie_jars/new
  # GET /cookie_jars/new.json
  def new
    @cookie_jar = CookieJar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cookie_jar }
    end
  end

  # GET /cookie_jars/1/edit
  def edit
    @cookie_jar = CookieJar.find(params[:id])
  end

  # POST /cookie_jars
  # POST /cookie_jars.json
  def create
    @cookie_jar = CookieJar.new(params[:cookie_jar])

    respond_to do |format|
      if @cookie_jar.save
        format.html { redirect_to @cookie_jar, notice: 'Cookie jar was successfully created.' }
        format.json { render json: @cookie_jar, status: :created, location: @cookie_jar }
      else
        format.html { render action: "new" }
        format.json { render json: @cookie_jar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cookie_jars/1
  # PUT /cookie_jars/1.json
  def update
    @cookie_jar = CookieJar.find(params[:id])

    respond_to do |format|
      if @cookie_jar.update_attributes(params[:cookie_jar])
        format.html { redirect_to @cookie_jar, notice: 'Cookie jar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cookie_jar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookie_jars/1
  # DELETE /cookie_jars/1.json
  def destroy
    @cookie_jar = CookieJar.find(params[:id])
    @cookie_jar.destroy

    respond_to do |format|
      format.html { redirect_to cookie_jars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookie_jars_helper.rb
module CookieJarsHelper
end

app/views/cookie_jars/_form.html.erb
<%= form_for(@cookie_jar) do |f| %>
  <% if @cookie_jar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookie_jar.errors.count, "error") %> prohibited this cookie_jar from being saved:</h2>

      <ul>
      <% @cookie_jar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookie_jars/edit.html.erb
<h1>Editing cookie_jar</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookie_jar %> |
<%= link_to 'Back', cookie_jars_path %>

app/views/cookie_jars/index.html.haml
%center
  %h1 My Wifi Cookie Jar
  %h2 ELEC3607 Arduino Project
  %h3 by Khanh Nguyen and Kevin Nguyen

  %img{:alt => "Cookie Jar is at #{@the_cookie_jar.level}%", :height => "500", :src => "cookie#{@level}.png", :width => "500"}

  .barcontainer
    .progress.progress-success.progress-striped.active
      .bar{:style => "width: #{@the_cookie_jar.level}%;"}
    %center= "My cookie jar is #{@the_cookie_jar.level}% full."

%h1 Listing cookie_jars
%table
  %tr
    %th Level
    %th
    %th
    %th
  - @cookie_jars.each do |cookie_jar|
    %tr
      %td= cookie_jar.level
      %td= link_to 'Show', cookie_jar
      %td= link_to 'Edit', edit_cookie_jar_path(cookie_jar)
      %td= link_to 'Destroy', cookie_jar, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Cookie jar', new_cookie_jar_path

app/views/cookie_jars/new.html.erb
<h1>New cookie_jar</h1>

<%= render 'form' %>

<%= link_to 'Back', cookie_jars_path %>

app/views/cookie_jars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Level:</b>
  <%= @cookie_jar.level %>
</p>


<%= link_to 'Edit', edit_cookie_jar_path(@cookie_jar) %> |
<%= link_to 'Back', cookie_jars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Wifi Cookie Jar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>